Uploaded all code created so far
When trying to join a channel the user is in, prints an error:
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Cian McDermott\eclipse-workspace\Discord Audio Bot\src\command.py", line 20, in join
    if ctx.author.voice is None:
AttributeError: 'User' object has no attribute 'voice'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'User' object has no attribute 'voice'

More features to add in the future:
-Audio mixing of music and sfx files to play both at once.
-Retrieving audio from Youtube or Spotify urls.
-Dropdown menu in player to select audio files from a list.